### ISSUE TITLE
How to us this with wine?

### ISSUE THREAD

**Issue by danisla** [piastry/etercifs#1]
@piastry do I need a custom build or patch for wine to use the locking features that etercifs provides?

Thanks!

**Comment by piastry** [comment]
Yes. Adding @vitlav to comment.

**Comment by danisla** [comment]
Thanks, would love to hear details on where to find the patched wine or how to patch it. 

Also, @piastry any chance of porting this to a 5.x kernel?

**Comment by piastry** [comment]
No plans. There is an outdated doc describing the process of adding new kernels: https://wiki.etersoft.ru/Etercifs/devel-eng. Feel free to refer to it and make the change. Pull requests are welcome.

Also note that there is a more up-to-date version of the repository: https://github.com/Etersoft/etercifs.

**Comment by vitlav** [comment]
Since kernel 4.11 they mask unknown flags with
flags &= VALID_OPEN_FLAGS;
so we need patch kernel to allow etercifs works (not just build a module).

Here is detailed description (in russian):
https://unixforum.org/viewtopic.php?f=58&p=1324496

**Comment by danisla** [comment]
Good to know about the flags on the 4.11+ kernels..

Here is log of the build errors I get when trying to use the 4.15 source to build on 5.3.0, if you were inclined to do a port.

```
  CC [M]  /tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.o
  CC [M]  /tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifssmb.o
  CC [M]  /tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifs_debug.o
  CC [M]  /tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.o
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c: In function 'cifs_put_tcp_session':
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c:2234:3: error: too many arguments to function 'force_sig'
   force_sig(SIGKILL, task);
   ^~~~~~~~~
In file included from /tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c:24:0:
./include/linux/sched/signal.h:341:13: note: declared here
 extern void force_sig(int);
             ^~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:903:17: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .atomic_open = cifs_atomic_open,
                 ^~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:903:17: note: (near initialization for 'cifs_dir_inode_ops.atomic_open')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1077:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1077:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1077:22: note: (near initialization for 'cifs_file_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1077:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1077:22: note: (near initialization for 'cifs_file_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1095:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1095:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1095:22: note: (near initialization for 'cifs_file_strict_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1095:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1095:22: note: (near initialization for 'cifs_file_strict_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1113:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1113:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1113:22: note: (near initialization for 'cifs_file_direct_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1113:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1113:22: note: (near initialization for 'cifs_file_direct_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1131:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1131:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1131:22: note: (near initialization for 'cifs_file_nobrl_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1131:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1131:22: note: (near initialization for 'cifs_file_nobrl_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1148:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1148:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1148:22: note: (near initialization for 'cifs_file_strict_nobrl_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1148:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1148:22: note: (near initialization for 'cifs_file_strict_nobrl_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1165:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1165:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1165:22: note: (near initialization for 'cifs_file_direct_nobrl_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1165:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1165:22: note: (near initialization for 'cifs_file_direct_nobrl_ops.remap_file_range')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1177:3: error: 'const struct file_operations' has no member named 'clone_file_range'; did you mean 'copy_file_range'?
  .clone_file_range = cifs_clone_file_range,
   ^~~~~~~~~~~~~~~~
   copy_file_range
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1177:22: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  .clone_file_range = cifs_clone_file_range,
                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1177:22: note: (near initialization for 'cifs_dir_ops')
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1177:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.c:1177:22: note: (near initialization for 'cifs_dir_ops.remap_file_range')
cc1: some warnings being treated as errors
scripts/Makefile.build:288: recipe for target '/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.o' failed
make[1]: *** [/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/cifsfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c: In function 'cifs_parse_mount_options':
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c:1713:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    if (!(tmp_end < end && tmp_end[1] == delim)) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.c:1720:3: note: here
   case Opt_pass:
   ^~~~
scripts/Makefile.build:288: recipe for target '/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.o' failed
make[1]: *** [/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke/connect.o] Error 1
Makefile:1655: recipe for target '_module_/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke' failed
make: *** [_module_/tmp/Etercifs.7DP7zOrw/5.3.0-1016-gke] Error 2
make: Leaving directory '/usr/src/linux-headers-5.3.0-1016-gke'
```
